# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 354af4bf283af0e5742c41f2ea0a362944fd34832800e57ceecfc49dd413c89529540605cca273e74b2588c4716f9ee97f1cdf4f84bfc7ba70f93cf4b2787947

test:
  secret_key_base: ddd3a57ab56f4c217caf32fea95effc0eafa94362954e9a1e5fa454f5d590c2e89195003c26e896abd04b72650b16705aab968c78ede7c6642a93fb1beafc9a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>


access_key_id: AKIAIUREKE3SKTGF6C5Q
secret_access_key: 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
